// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJcn9W2HNMXEwYCqLH0ILQVp4UN2eZ5H4',
    appId: '1:675203738028:android:0c3ef15486f6c2bdeab209',
    messagingSenderId: '675203738028',
    projectId: 'sleep-deep',
    storageBucket: 'sleep-deep.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1VGUkbHZybk2TB6FdPLDLh2dFXRgYQnw',
    appId: '1:675203738028:ios:1b561f2f38e586aaeab209',
    messagingSenderId: '675203738028',
    projectId: 'sleep-deep',
    storageBucket: 'sleep-deep.firebasestorage.app',
    iosBundleId: 'com.example.flutterProyectoFinal',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI36UqjCBBn62zxNJWtbO2tbm7Fm_gL1c',
    appId: '1:675203738028:web:ebb3f08c0ccb8dceeab209',
    messagingSenderId: '675203738028',
    projectId: 'sleep-deep',
    authDomain: 'sleep-deep.firebaseapp.com',
    storageBucket: 'sleep-deep.firebasestorage.app',
    measurementId: 'G-81V80JFFBS',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI36UqjCBBn62zxNJWtbO2tbm7Fm_gL1c',
    appId: '1:675203738028:web:479279a01a200ac0eab209',
    messagingSenderId: '675203738028',
    projectId: 'sleep-deep',
    authDomain: 'sleep-deep.firebaseapp.com',
    storageBucket: 'sleep-deep.firebasestorage.app',
    measurementId: 'G-816292EKVS',
  );

}