name: flutter_proyecto_final
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.2 
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^12.0.0+1
  flutter_riverpod: ^2.6.1
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.4.4
  firebase_core: ^3.3.0
  firebase_auth: ^5.2.0
  flutter_colorpicker: ^1.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
